server:
  port: 8080

student:
  name: zhangsan
  age: 20
  claszz: {
    name: 1706
  }
  array: [10,20,30,40,50]

#spring:
#    mvc:
#        view:
#          prefix: /WEB-INF/jsp/
#          suffix: .jsp

#数据库连接
spring:
  datasource:
    #配置当前要使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.8.18:3306/idea?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis: #扫描 classpath:mybatis/Mapper/下所有的xml
  mapper-locations: classpath:mybatis/Mapper/*.xml
  type-aliases-package: classpath:com.znsd.springboot.entitys
